export const GET_GLOBAL_CORONA_DATA = 'GET_GLOBAL_CORONA_DATA';
export const GET_ALL_COUNTRIES_CORONA_DATA = 'GET_ALL_COUNTRIES_CORONA_DATA';
export const GET_SELECTED_COUNTRY = 'GET_SELECTED_COUNTRY';